[package]
name = "rommel"
version = "0.1.0"
edition = "2024"
description = "ROM memory layout generator for linker script generation"
homepage = "https://codeberg.org/bergzand/rommel/"
repository = "https://codeberg.org/bergzand/rommel/"
license = "MIT OR Apache-2.0"
categories = ["embedded"]

[dependencies]
itertools = "0.14.0"
ld-memory = "0.2.9"
microlp = "0.4.0"
serde = { version = "1.0.228", optional = true, features = ["derive"] }
thiserror = "2.0.18"
uom = { version = "0.38.0", features = ["si", "u64"] }

[features]
default = ["serde"]
serde = ["dep:serde", "uom/serde"]

[dev-dependencies]
clap = { version = "4.6.1", features = ["derive"] }
yaml_serde = "0.10.4"
