[package]
name = "memsolve"
version = "0.1.0"
edition = "2024"
description = "ROM memory layout solver for linker script generation"
homepage = "https://codeberg.org/bergzand/memsolve/"
repository = "https://codeberg.org/bergzand/memsolve/"
license = "MIT OR Apache-2.0"
keywords = ["linker"]
categories = ["development-tools::build-utils", "embedded"]

[[example]]
name = "multifile"
required-features = ["serde"]

[dependencies]
conv = "0.3.3"
itertools = "0.14.0"
ld-memory = "0.2.9"
microlp = "0.4.0"
serde = { version = "1.0.228", optional = true, features = ["derive"] }
thiserror = "2.0.18"
uom = { version = "0.38.0", optional = true, features = ["si", "u64"] }

[dev-dependencies]
clap = { version = "4.6.1", features = ["derive"] }
yaml_serde = "0.10.4"

[features]
default = ["serde"]
serde = ["dep:serde", "dep:uom", "uom/serde"]
uom = ["dep:uom"]

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
